//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisite
    {
        public string Course_ID { get; set; }
        public string Requisite_ID { get; set; }
        public string Requisite1 { get; set; }
        public string Requisite11 { get; set; }
    }
}
